- name: install emacs
  package:
    name:
      - emacs
      
- name: download doom
  become_user: philipp
  git:
    repo: 'https://github.com/doomemacs/doomemacs'
    dest: '~/.config/emacs'
    depth: 1
    
- name: make sure .emacs.d is deleted
  become_user: philipp
  file:
    path: '~/.emacs.d'
    state: absent
    
- name: create .local/bin/doom
  become_user: philipp
  file:
    path: '~/.local/bin/'
    state: directory
    owner: philipp
    group: philipp

- name: symlink doom bin
  become_user: philipp
  file:
    src: '~/.config/emacs/bin/{{ item }}'
    dest: '~/.local/bin/{{ item }}'
    state: link
  loop:
    - doom
    - doomscript
    - org-capture
    - org-tangle

#- name: install doom emacs
#  become_user: philipp
#  expect:
#    command: bash -c '~/.config/emacs/bin/doom install'
#    responses:
#      "Download and install all-the-icon's fonts? (y or n) ": "n"

- name: load custom doom config
  copy:
    src: 'doom/{{ item }}'
    dest: '/home/philipp/.config/doom/{{ item }}'
    owner: philipp
    group: philipp
    mode: 0600
  loop:
    - init.el
    - config.el
    
- name: sync doom emacs
  become_user: philipp
  shell: '~/.config/emacs/bin/doom sync'
