- name: install emacs
  package:
    name:
      - emacs
      
- name: download doom
  become_user: philipp
  git:
    repo: 'https://github.com/doomemacs/doomemacs'
    dest: '~/.config/emacs'
    depth: 1
    
- name: make sure .emacs.d is deleted
  become_user: philipp
  file:
    path: '~/.emacs.d'
    state: absent
    
- name: create .local/bin/doom
  become_user: philipp
  file:
    path: '~/.local/bin/'
    state: directory
    owner: philipp
    group: philipp

- name: symlink doom bin
  become_user: philipp
  file:
    src: '~/.config/emacs/bin/{{ item }}'
    dest: '~/.local/bin/{{ item }}'
    state: link
  loop:
    - doom
    - doomscript
    - org-capture
    - org-tangle

- name: Install Doom Emacs
  become_user: philipp
  expect:
    command: bash -c "~/.config/emacs/bin/doom install"
    responses:
      "Download and install all-the-icon's fonts? (y or n) ": 'y'

- name: load custom doom config
  become_user: philipp
  file:
    src: 'files/doom/init.el'
    dest: '~/.config/doom/init.el'
