- name: install emacs
  package:
    name:
      - emacs
      
- name: download doom
  become_user: philipp
  git:
    repo: 'https://github.com/doomemacs/doomemacs'
    dest: '~/.config/emacs'
    depth: 1
    
- name: make sure .emacs.d is deleted
  become_user: philipp
  file:
    path: '~/.emacs.d'
    state: absent
    
- name: create .local/bin/doom
  become_user: philipp
  file:
    path: '~/.local/bin/'
    state: directory
    owner: philipp
    group: philipp

- name: symlink doom bin
  become_user: philipp
  file:
    src: '~/.config/emacs/bin/{{ item }}'
    dest: '~/.local/bin/.'
  loop:
    - doom
    - doomscript
    - org-capture
    - org-tangle
