- name: add flathub flatpak repository
  become_user: philipp
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user

- name: install flatpaks
  become_user: philipp
  flatpak:
    name: "{{ item }}"
    method: user
    state: present
  loop:
    - com.valvesoftware.Steam
    - com.valvesoftware.Steam.CompatibilityTool.Proton
