- name: install packages
  package:
    name:
      - python3-pip
      - python3.8
      - python3.9
      - python3.10
      - python3.11

- name: install additional packages to system python
  pip:
    name:
      - numpy
      - matplotlib
      - pandas
      - scipy
