- name: add flathub flatpak repository
  become_user: philipp
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user

- name: install signal from flatpak
  become_user: philipp
  flatpak:
    name: org.signal.Signal
    method: user
    state: present
